/** Thin fetch wrapper for client components: JSON in/out, throws a readable Error on non-2xx. */
export async function apiFetch<T = unknown>(url: string, init?: RequestInit): Promise<T> {
  // FormData must set its own Content-Type: the multipart boundary is
  // generated by fetch and forcing "application/json" here produces a body the
  // server cannot parse, with no useful error.
  const isFormData = typeof FormData !== "undefined" && init?.body instanceof FormData;

  const res = await fetch(url, {
    ...init,
    headers: isFormData ? init?.headers : { "Content-Type": "application/json", ...init?.headers },
  });

  if (!res.ok) {
    const body = await res.json().catch(() => null);
    throw new Error(body?.error || `Request failed (${res.status})`);
  }

  if (res.status === 204) return undefined as T;
  return res.json();
}
